import {EVENTS_PAGE_LIST_DECLARATIONS} from './pagelist/';
import {EVENTS_PAGE_DETAILS_DECLARATIONS} from './pagedetails';

export const EVENTS_DECLARATIONS = [
    ...EVENTS_PAGE_LIST_DECLARATIONS,
    ...EVENTS_PAGE_DETAILS_DECLARATIONS
];
